import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class SharedService {
  cityOptions: string[] = [
    'Toronto',
    'Ottawa',
    'Vancover',
    'Paris',
    'London',
    'New York',
    'Tokyo',
    'Rome',
    'Sydney',
    'Dubai',
    'Moscow',
    'Beijing',
    'Istanbul',
    'Cairo',
    'Cape Town',
    'Barcelona',
    'Mumbai',
    'Berlin',
    'Buenos Aires',
    'Bangkok',
    'Delhi'];  // City lists

  weatherConditions: string[] = [
    'relativehumidity_2m',
    'dewpoint_2m',
    'apparent_temperature',
    'precipitation_probability',
    'precipitation',
    'rain',
    'showers',
    'snowfall',
    'snow_depth',
    'weathercode',
    'pressure_msl',
    'surface_pressure',
    'cloudcover',
    'cloudcover_low',
    'cloudcover_mid',
    'cloudcover_high',
    'visibility',
    'evapotranspiration',
    'et0_fao_evapotranspiration',
    'vapor_pressure_deficit',
    'windspeed_10m',
    'windspeed_80m',
    'windspeed_120m',
    'windspeed_180m',
    'winddirection_10m',
    'winddirection_80m',
    'winddirection_120m',
    'winddirection_180m',
    'windgusts_10m',
    'temperature_80m',
    'temperature_120m',
    'temperature_180m',
    'soil_temperature_0cm',
    'soil_temperature_6cm',
    'soil_temperature_18cm',
    'soil_temperature_54cm',
    'soil_moisture_0_1cm'
  ]


  weatherCodes = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog and depositing rime fog",
    48: "Fog and depositing rime fog",
    51: "Light intensity Drizzle",
    53: "Drizzle: Moderate intensity",
    55: "Drizzle: Dense intensity",
    56: "Freezing Drizzle: Light intensity",
    57: "Freezing Drizzle: Dense intensity",
    61: "Rain: Slight intensity",
    63: "Rain: Moderate intensity",
    65: "Rain: Heavy intensity",
    66: "Freezing Rain: Light intensity",
    67: "Freezing Rain: Heavy intensity",
    71: "Snow fall: Slight intensity",
    73: "Snow fall: Moderate intensity",
    75: "Snow fall: Heavy intensity",
    77: "Snow grains",
    80: "Rain showers: Slight intensity",
    81: "Rain showers: Moderate intensity",
    82: "Rain showers: Violent intensity",
    85: "Snow showers: Slight intensity",
    86: "Snow showers: Heavy intensity",
    95: "Thunderstorm: Slight or moderate",
    96: "Thunderstorm with slight hail",
    99: "Thunderstorm with heavy hail",
  };
  constructor() { }
}
